meta_product_name: "Rémi Créations"
meta_title: "Rémi Créations - Réalisation de pièces uniques"
meta_description: "Rémi Créations propose la réalisation de pièces uniques en verre et en argile. Des oeuvres en vitrail ou sculptées, réalisées à la main et destinées à la décoration d'intérieur."
meta_image: "logo-remi-vert.png" # should exist in `app/assets/images/`
